[package]
name = "trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
imm-cee-tee-ess = { path = "../" }
# bullet = { package = "bullet_lib", features = ["cuda"], git = "https://github.com/jw1912/bullet" }
bullet = { package = "bullet_lib", git = "https://github.com/jw1912/bullet" }
